spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    hibernate:
      show-sql: true
      format-sql: true
      ddl-auto: create
    generate-ddl: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate:
        ejb:
          use_class_enhancer: true
logging:
  level:
    org:
      hibernate:
        type: trace